default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: coupon_development
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: coupon_test

production:
  <<: *default
